# Generated by Django 4.2.7 on 2023-11-30 02:39

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(default=datetime.datetime(2023, 11, 29, 22, 39, 40, 703476))),
                ('nationality', models.CharField(choices=[('USA', 'Estados Unidos'), ('BR', 'Brasil')], default='USA', max_length=100)),
            ],
        ),
    ]
